config/routes.rb
Rails.application.routes.draw do
  resources :kudos
  resources :organizations
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root 'kudos#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :organizations do
    get :join_org
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kudo.rb
class Kudo < ApplicationRecord
  belongs_to    :sender, 
                class_name: "User"

  belongs_to    :receiver, 
                class_name: "User"

  validates :message, presence: true

end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :sender, 
            class_name: 'Kudo',
            foreign_key: 'sender_id'

  has_many  :receiver, 
            class_name: 'Kudo',
            foreign_key: 'receiver_id'
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kudos_controller.rb
class KudosController < ApplicationController
  before_action :set_kudo, :require_login, only: [:show, :edit, :update, :destroy]
  
  # GET /kudos
  # GET /kudos.json
  def index
    @kudos = Kudo.all
  end

  # GET /kudos/1
  # GET /kudos/1.json
  def show
  end

  # GET /kudos/new
  def new
    @kudo = Kudo.new
  end

  # GET /kudos/1/edit
  def edit
  end

  # POST /kudos
  # POST /kudos.json
  def create
    @kudo = Kudo.new(kudo_params.merge(sender_id: current_user.id))

    respond_to do |format|
      if @kudo.save
        format.html { redirect_to kudos_url, notice: 'Kudos was sent.' }
        format.json { render :show, status: :created, location: @kudo }
      else
        format.html { render :new }
        format.json { render json: @kudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kudos/1
  # PATCH/PUT /kudos/1.json
  def update
    respond_to do |format|
      if @kudo.update(kudo_params)
        format.html { redirect_to @kudo, notice: 'Kudo was successfully updated.' }
        format.json { render :show, status: :ok, location: @kudo }
      else
        format.html { render :edit }
        format.json { render json: @kudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kudos/1
  # DELETE /kudos/1.json
  def destroy
    @kudo.destroy
    respond_to do |format|
      format.html { redirect_to kudos_url, notice: 'Kudo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kudo
      @kudo = Kudo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kudo_params
      params.require(:kudo).permit(:message, :sender_id, :receiver_id)
    end

    def require_login
      unless current_user
        redirect_to login_url
      end
    end
  
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params.merge(user_id: current_user.id))
      if @organization.save
        create_and_join_org(@organization)
      else
        respond_to do |format|
          format.html { render :new }
          format.json { render json: @organization.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_and_join_org(organization)
    current_user.update_attribute(:organization_id, organization.id)

    respond_to do |format|
      format.html { redirect_to kudos_path, notice: 'Successfully created and joined that organization.' }
      format.json { render :show, status: :created, location: @organization }
    end
  end

  def join_org(organization=params[:organization_id])
    @org = Organization.find(organization)
    current_user.update_attribute(:organization_id, @org.id)

    respond_to do |format|
      format.html { redirect_to kudos_path, notice: 'You have joined that organization.' }
      format.json { render :show, status: :created, location: @organization }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :description, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:full_name, :email, :password, :password_confirmation, :current_password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kudos_helper.rb
module KudosHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/kudos/_form.html.erb
<%= form_with(model: kudo, local: true) do |form| %>
  <% if kudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kudo.errors.count, "error") %> prohibited this kudo from being saved:</h2>

      <ul>
      <% kudo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="field">
    <%= form.label :receiver_id %>
    <%= form.collection_select :receiver_id, User.where.not(id: current_user).where(organization_id: current_user.organization_id), :id, :full_name %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-success my-2 my-sm-0" %>
  </div>
<% end %>

app/views/kudos/edit.html.erb
<h1>Editing Kudo</h1>

<%= render 'form', kudo: @kudo %>

<%= link_to 'Show', @kudo %> |
<%= link_to 'Back', kudos_path %>

app/views/kudos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="starter-template">
  <% @kudos_left = 3 - current_user.sender.where(created_at: Date.today.beginning_of_week...Date.today.end_of_week).count %>
  <% if !current_user.organization_id.present? %> 
    <h6> Join or create an organization above</h6>
    <% elsif @kudos_left > 0 && current_user.organization_id.present? %>
      <%= link_to 'Send a Kudos', new_kudo_path, class: "btn btn-outline-success my-2 my-sm-0"%>
      <p> <h6> <%= @kudos_left %> Kudos left to give! </h6>
    <% else %> 
      <p> <h6> Kudos reload weekly! </h6>
  <% end %>
</div>

  <div class="centered">
    <% if current_user.receiver.count > 0 %>
    <table class="kudos" style="width:450px;">
      <thead>
        <tr>
          <th>Kudos to you:</th>
          <th>From:</th>
        </tr>
      </thead>

      <tbody>
        <% current_user.receiver.reverse_order.each  do |kudo| %>
          <tr>
            <td><%= kudo.message %></td>
            <% @sender = User.find(kudo.sender.id) %>
            <td> <%= @sender.full_name %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% else %> 
      <h6> Still awaiting your first kudo, get out there and help a teammate! </h6>
    <% end %>
  </div>

<br>

app/views/kudos/new.html.erb
<div class="starter-template">
    <h5>New Kudo</h5>
    <%= render 'form', kudo: @kudo %>
</div>

app/views/kudos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @kudo.message %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @kudo.sender %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @kudo.receiver %>
</p>

<%= link_to 'Edit', edit_kudo_path(@kudo) %> |
<%= link_to 'Back', kudos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoworkerKudos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <nav class="navbar navbar-expand-md navbar-default bg-light fixed-top">
            <li class="navbar-brand" href="#"><%= link_to 'Kudos', kudos_path %> </li>
          
            <div class="navbar-nav ml-auto">
              <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                  <% if user_signed_in? %>
                    <% if current_user.organization_id.present? %>
                      <li class="nav-item active"> User: <%= current_user.email %>&nbsp;|&nbsp;Team: <%= link_to Organization.find(current_user.organization_id).name, organizations_path %>&nbsp;|&nbsp;</li>
                      <% else %>
                        <li class="nav-item active"> <%= current_user.email %> | <%= link_to 'Join or Create an Org', organizations_path %>&nbsp;|&nbsp;</li>
                    <% end %>
                      <li class="nav-item active"> <%= link_to " Sign Out", destroy_user_session_path %>  </li>
                  <% end %>
              </ul>
            </div>
          </nav>

        <main role="main" class="container">
            <div>
                <%= yield %>
            </div>
        </main>

  </body>
</html>

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-success my-2 my-sm-0" %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>
<div class="starter-template">
<h5>Organizations</h5>
<%= link_to 'New Organization', new_organization_path, class: "btn btn-outline-success my-2 my-sm-0"%>
</div>
<div class="centered">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Join</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @organizations.each do |organization| %>
        <tr>
          <td><%= organization.name %></td>
          <td><%= organization.description %></td>
          <td><%= link_to 'Join', organization_join_org_path(organization) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/organizations/new.html.erb
<div class="starter-template">
    <h5>New Organization</h5>
    <%= render 'form', organization: @organization %>
</div>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @organization.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @organization.user %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>